site_name: Managing Content in MyLife
copyright: 'Copyright (c) 2016 OLM Systems'

# Navigation
pages:
- Introduction: index.md
- Umbraco Orientation: orientation/index.md
- Settings: settings/index.md
- Managing Content: file-management/index.md
- Managing Assets TODO: asset-management/index.md
- Menus: menus/index.md
- Content Articles: content-articles/index.md
- Menu Pages TODO: menu-pages/index.md
- Guides TODO: guides/index.md
- Page Layouts TODO: page-layout/index.md
- Widgets TODO: widgets/index.md

# Options
theme: 'material'
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'

# Extensions
markdown_extensions:
  - admonition